### ISSUE TITLE
图片没有上下居中是什么原因 我显示的总是在最顶上

### ISSUE THREAD

**Issue by qianqikun** [yanghuiLu/previewImage-mobile#11]

**Comment by Mr-Hawthorn** [comment]
+1 老哥解决了吗

**Comment by shitalo** [comment]
同，图片始终会显示在最顶上，而不是垂直居中。

原因：受用户代理样式表影响。会使得 body 的 display 被设置为 block，导致 

```css
#__previewImage-container .previewImage-box .previewImage-item .previewImage-image {
    vertical-align: middle;
}
```
无法生效。

解决办法：在html文件头部添加 `<!DOCTYPE html>` 声明，即可解决。
